services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_DB=practice
      - MYSQL_USER=practice
      - MYSQL_PASS=practice
      - MYSQL_HOST=mysql
  mysql:
    image: mysql:8.0
    restart: always
    platform: linux/amd64
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: practice
      MYSQL_USER: practice
      MYSQL_PASSWORD: practice
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
