server:
  port: 8080
  shutdown: graceful

spring:
  application.name: practice-java-spring-boot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/practice-java-spring-boot
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
      open-in-view: false
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true

