server:
  port: 8080
  shutdown: graceful

spring:
  application.name: practice-java-spring-boot
  datasource:
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/practice
      username: root
      password: root
    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/practice
      username: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  zipkin:
    enabled: true
    base-url: http://localhost:9411

management:
  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

kafka:
  producer:
    bootstrap-servers: localhost:9092
    topics:
      create-product: "create-product"

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
